---
version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "monthly"
    rebase-strategy: "disabled"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "07:00"
      timezone: "Europe/Rome"
  - package-ecosystem: "pip"
    directory: ".github/workflows"
    schedule:
      interval: "monthly"
    rebase-strategy: "disabled"
