[package]
name         = "rustracer"
license      = "GPL-3.0"
version      = "0.1.0"
edition      = "2021"
rust-version = "1.60"
authors      = [
   "Andrea Rossoni <andrea dot ros.21 at e.email>",
   "Paolo Azzini <paolo dot azzini1 at gmail.com>"
]
readme       = "README.md"
repository   = "https://github.com/andros21/rustracer"
homepage     = "https://github.com/andros21/rustracer"
categories   = ["command-line-utilities"]
description  = "cli photorealistic image generator"
keywords     = [
   "cli",
   "generator",
   "image",
   "photo",
   "raytracer",
   "raytracing",
   "realistic",
]

[[bin]]
name = "rustracer"
path = "src/main.rs"

[dependencies]
thiserror = "1.0.30"
byteorder = "1.4.3"

[dependencies.image]
version          = "0.24.1"
default-features = false
features         = ["farbfeld", "png"]

[dependencies.clap]
version          = "3.1.14"
default-features = false
features         = ["std", "suggestions", "wrap_help"]
