match_block_trailing_comma = true
use_field_init_shorthand   = true
use_try_shorthand          = true
newline_style              = "Unix"

# Unstable options that help catching some mistakes in formatting
# and that we may want to enable when they become stable.
#
# They are kept here since they are useful to run from time to time.
#
# format_code_in_doc_comments = true
# reorder_impl_items = true
# comment_width = 100
# wrap_comments = true
# normalize_comments = true
# format_strings = true
# imports_granularity = "Crate"
