---
name: CD

"on":
  push:
    tags:
      - "[0-9].[0-9].[0-9]+"

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: checkout project
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
      - name: check cargo cache
        uses: actions/cache@58c146cc91c5b9e778e71775dfe9bf1442ad9a12
        id: rust-cache
        with:
          path: |
            ~/.cargo/
            ~/.rustup/
            target/
          key: ${{ runner.os }}-rust-musl-${{ hashFiles('Cargo.toml') }}-${{ hashFiles('Cargo.lock') }}
      - name: install rust toolchain
        if: steps.rust-cache.outputs.cache-hit != 'true'
        uses: dtolnay/rust-toolchain@e645b0cf01249a964ec099494d38d2da0f0b349f
        with:
          toolchain: stable
          targets: x86_64-unknown-linux-musl
      - name: cargo release
        run: |
          cargo build --locked --release --target x86_64-unknown-linux-gnu --target x86_64-unknown-linux-musl
      - name: assemble artifacts
        run: .github/workflows/cd.sh assemble
      - name: install cosign
        uses: sigstore/cosign-installer@9becc617647dfa20ae7b1151972e9b3a2c338a2b
      - name: cosign artifacts
        env:
          COSIGN_EXPERIMENTAL: 1
        run: .github/workflows/cd.sh cosign
      - name: release artifacts
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844
        with:
          generate_release_notes: true
          fail_on_unmatched_files: true
          files: |
            rustracer-*.tar.gz
            rustracer-*.txt
            rustracer-*.pem
            rustracer-*.sig
  cratesio:
    name: cratesio
    runs-on: ubuntu-latest
    permissions:
      contents: read
    needs:
      - release
    environment:
      name: cratesio
      url: https://crates.io/crates/rustracer
    steps:
      - name: checkout project
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
      - name: check cache
        uses: actions/cache@58c146cc91c5b9e778e71775dfe9bf1442ad9a12
        id: cache
        with:
          path: |
            ~/.cargo/
            ~/.rustup/
            target/
          key: ${{ runner.os }}-rust-all-${{ hashFiles('Cargo.toml') }}-${{ hashFiles('Cargo.lock') }}
      - name: install rust toolchain
        if: steps.cache.outputs.cache-hit != 'true'
        uses: dtolnay/rust-toolchain@e645b0cf01249a964ec099494d38d2da0f0b349f
        with:
          toolchain: stable
          components: clippy, llvm-tools-preview, rustfmt, rust-docs
      - name: cargo publish
        run: |
          cargo publish --locked
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
  ghpages:
    name: ghpages
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs:
      - cratesio
    steps:
      - name: checkout project
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
      - name: check cache
        uses: actions/cache@58c146cc91c5b9e778e71775dfe9bf1442ad9a12
        id: cache
        with:
          path: |
            ~/.cargo/
            ~/.rustup/
            target/
          key: ${{ runner.os }}-rust-all-${{ hashFiles('Cargo.toml') }}-${{ hashFiles('Cargo.lock') }}
      - name: install rust toolchain
        if: steps.cache.outputs.cache-hit != 'true'
        uses: dtolnay/rust-toolchain@e645b0cf01249a964ec099494d38d2da0f0b349f
        with:
          toolchain: stable
          components: clippy, llvm-tools-preview, rustfmt, rust-docs
      - name: patch and cargo rustdoc
        run: make rust_docs
      - name: publish to gh-pages
        uses: peaceiris/actions-gh-pages@64b46b4226a4a12da2239ba3ea5aa73e3163c75b
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: target/doc/
