---
name: CI

"on":
  push:
    branches:
      - master
    paths:
      - 'Cargo.lock'
      - 'Cargo.toml'
      - 'src/**'
  pull_request:
    branches:
      - master
    paths:
      - 'Cargo.lock'
      - 'Cargo.toml'
      - 'src/**'

permissions:
  contents: read

jobs:
  lint:
    name: lint ci
    runs-on: ubuntu-latest
    steps:
      - name: checkout project
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
      - name: check cache
        uses: actions/cache@4b0cf6cc4619e737324ddfcec08fff2413359514
        id: cache
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-rustdoc-${{ hashFiles('**/Cargo.lock') }}
      - name: install rust toolchain
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions-rs/toolchain@568dc894a7f9e32ffd9bb7d7a6cebb784cdaa2b0
        with:
          toolchain: stable
          default: true
          profile: minimal
          components: rustfmt, clippy, rust-docs
      - name: cargo fmt check
        uses: actions-rs/cargo@4ff6ec2846f6e7217c1a9b0b503506665f134c4b
        with:
          command: fmt
          args: -- --check --verbose
      - name: cargo clippy main
        uses: actions-rs/cargo@4ff6ec2846f6e7217c1a9b0b503506665f134c4b
        with:
          command: clippy
          args: --locked --workspace
      - name: cargo clippy tests
        uses: actions-rs/cargo@4ff6ec2846f6e7217c1a9b0b503506665f134c4b
        with:
          command: clippy
          args: --locked --tests
      - name: cargo rustdoc
        uses: actions-rs/cargo@4ff6ec2846f6e7217c1a9b0b503506665f134c4b
        with:
          command: rustdoc
  test:
    name: test ci
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: checkout project
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
      - name: check cache
        uses: actions/cache@4b0cf6cc4619e737324ddfcec08fff2413359514
        id: cache
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-rustdoc-${{ hashFiles('**/Cargo.lock') }}
      - name: install rust toolchain
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions-rs/toolchain@568dc894a7f9e32ffd9bb7d7a6cebb784cdaa2b0
        with:
          toolchain: stable
          default: true
          profile: minimal
      - name: install llvm-tools-preview
        run: |
          rustup toolchain install stable --component llvm-tools-preview
      - name: install cargo-llvm-cov
        uses: taiki-e/install-action@977df53448dfb22dd55db0e45022238d245eb72b
        with:
          tool: cargo-llvm-cov
      - name: cargo build
        uses: actions-rs/cargo@4ff6ec2846f6e7217c1a9b0b503506665f134c4b
        with:
          command: build
          args: --locked
      - name: cargo test coverage
        uses: actions-rs/cargo@4ff6ec2846f6e7217c1a9b0b503506665f134c4b
        with:
          command: llvm-cov
          args: --locked --tests --lcov --output-path lcov.info
      - name: codecov coverage
        uses: codecov/codecov-action@3ffc51ef27c7ddc5ff57a2472a0c628d0fcb25c9
        with:
          files: lcov.info
          fail_ci_if_error: true
